#springboot启动端口
server:
  port: 8088
#ActiveMQ配置
spring:
  activemq:
    broker-url: tcp://192.168.67.130:61616 #ActiveMQ服务器IP
    user: admin #ActiveMQ连接用户名
    password: admin #ActiveMQ连接密码
  jms:
    #指定连接队列还是主题
    pub-sub-domain: false  #false=Queue，true=Topic
#定义服务上的队列名称
myQueueName: springboot-activemq-queue
